mat_zavody/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('zavody/', include('zavody.urls')),
    path('', RedirectView.as_view(url='zavody/')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zavody/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('kluby/', views.KlubListView.as_view(), name='seznam_klubu'),
    path('kluby/<int:pk>', views.KlubDetailView.as_view(), name='detail_klubu'),
]

zavody/models.py
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.db import models


class Klub(models.Model):
    nazev = models.CharField(max_length=50, verbose_name='Název klubu', help_text='Zadejte název klubu',
                             error_messages={'blank': 'Název klubu musí být vyplněn'})
    misto = models.CharField(max_length=30, verbose_name='Město (obec)', help_text='Zadejte jméno města nebo obce',
                             error_messages={'blank': 'Jméno města nebo obce musí být vyplněno'})
    zalozeni = models.IntegerField(blank=True, validators=[MinValueValidator(1900), MaxValueValidator(2023)], verbose_name='Rok založení',
                                   help_text='Zadejte rok založení')
    logo = models.ImageField(blank=True, upload_to='loga', verbose_name='Logo klubu', help_text='Zadejte logo klubu')

    class Meta:
        ordering = ['nazev']
        verbose_name = 'Klub'
        verbose_name_plural = 'Kluby'

    def __str__(self):
        return f'{self.nazev}, {self.misto}'


class Cyklista(models.Model):
    jmeno = models.CharField(max_length=50, verbose_name='Jméno', help_text='Zadejte jméno cyklisty',
                             error_messages={'blank': 'Jméno cyklisty musí být vyplněno'})
    prijmeni = models.CharField(max_length=50, verbose_name='Příjmení', help_text='Zadejte příjmení cyklisty',
                                error_messages={'blank': 'Příjmení cyklisty musí být vyplněno'})
    narozeni = models.DateField(blank=True, verbose_name='Datum narození', help_text='Zadejte datum narození')
    fotka = models.ImageField(blank=True, upload_to='fotky', verbose_name='Fotka cyklisty')
    kariera = models.TextField(blank=True, verbose_name='Kariéra')
    klub = models.ForeignKey('Klub', on_delete=models.CASCADE, verbose_name='Klub')

    class Meta:
        ordering = ['prijmeni', 'jmeno']
        verbose_name = 'Cyklista'
        verbose_name_plural = 'Cyklisté'

    def __str__(self):
        return f'{self.prijmeni}, {self.jmeno}'


class Zavod(models.Model):
    nazev = models.CharField(max_length=100, verbose_name='Název závodu', help_text='Zadejte název zavodu',
                             error_messages={'blank': 'Název závodu musí být vyplněn'})
    datum_konani = models.DateField(verbose_name='Datum konání', help_text='Zadej datum konání závodu',
                                    error_messages={'blank': 'Datum konání závodu musí být vyplněno'})
    ucastnici = models.ManyToManyField('Cyklista', verbose_name='Účastníci závodu', blank=True)
    klub = models.ForeignKey('Klub', on_delete=models.CASCADE, verbose_name='Klub pořádající závod')
    informace = models.TextField(blank=True, verbose_name='Podrobnější informace')
    delka = models.PositiveIntegerField(blank=True, validators=[MinValueValidator(1), MaxValueValidator(300)],
                                verbose_name='Délka trasy', help_text='Zadejte délku trasy závodu v rozsahu 1 - 300 km')

    class Meta:
        ordering = ['-datum_konani']
        verbose_name = 'Závod'
        verbose_name_plural = 'Závody'

    def __str__(self):
        return f'{self.datum_konani.day}. {self.datum_konani.month}. {self.datum_konani.year}: {self.nazev}, ({self.delka} km)'

zavody/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView

from .models import Cyklista, Zavod, Klub


def index(request):
    context = {
        'nadpis': 'BikeWeb',
        'cykliste': Cyklista.objects.order_by('-narozeni')[:4]
    }
    return render(request, 'index.html', context=context)


class KlubListView(ListView):
    model = Klub
    template_name ='kluby/list.html'
    context_object_name ='kluby'
    queryset = Klub.objects.order_by('nazev')


class KlubDetailView(DetailView):
    model = Klub
    template_name ='kluby/detail.html'
    context_object_name ='klub'

zavody/templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Cyklistika{% endblock %}</title>
    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <!-- Záhlaví -->
     {% include 'page/header.html' %}
    <!-- Navigace -->
    {% include 'page/navbar.html' %}
    <!-- Obsah stránky -->
    <main class="container">
    {% block content %}{% endblock %}
    </main>
    <!-- Zápatí -->
     {% include 'page/footer.html' %}
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'bootstrap/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    {% block script %}{% endblock %}
</body>
</html>

zavody/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 text-center bg-info mt-3 mb-3 box-rounded">
            <h2 class="text-white p-3">Naděje amatérského peletonu</h2>
        </div>
    {% for cyklista in cykliste %}
    <div class="col-lg-3 col-md-6 text-center">
        <p><img src="{{ cyklista.fotka.url }}" alt="{{ cyklista.prijmeni }}" class="img-fluid rounded-circle"></p>
        <h3><a href="#" class="btn btn-info">{{ cyklista.jmeno }} {{ cyklista.prijmeni|upper }}</a></h3>
        <p>Ročník: <b>{{ cyklista.narozeni.year }}</b></p>
        <p class="small">Oddíl: <b>{{ cyklista.klub }}</b></p>
    </div>
    {% endfor %}
    </div>
{% endblock %}

zavody/templates/kluby/detail.html
{% extends 'base.html' %}

{% block title %}
{{ klub }}
{% endblock %}

{% block content %}
    <h2 class="bg-secondary text-light text-center text-uppercase p-3">{{ klub.nazev.upper }}</h2>
    <div class="row">
        <div class="col-lg-4">
            <img src="{{ klub.logo.url }}" alt="Logo: {{ klub }}">
            <div class="bg-light p-3">
               <p>Místo: {{ klub.misto }}</p>
               <p>Rok založení: {{ klub.zalozeni }}</p>
            </div>
        </div>
        <div class="col-lg-8">
            <h3>Závodníci</h3>
            <div>
                {% for cyklista in klub.cyklista_set.all %}
                <div class="row">
                    <div class="col-md-4">
                        <img src="{{ cyklista.fotka.url }}" alt="{{ cyklista }}" class="img-fluid img-thumbnail">
                    </div>
                    <div class="col-md-8">
                        <h4>{{ cyklista.jmeno }} {{ cyklista.prijmeni.upper }}</h4>
                        <p>Narozen: {{ cyklista.narozeni }}</p>
                        <h5>Výsledky</h5>
                        <p class="bg-light p-3">{{ cyklista.kariera }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

zavody/templates/kluby/list.html
{% extends 'base.html' %}

{% block title %}
Přehled klubů
{% endblock %}

{% block content %}
    <h2 class="text-danger text-center text-uppercase m-3">Přehled klubů</h2>
    <div>
        <table class="table table-active table-hover table-responsive-lg">
            <thead class="bg-danger text-light">
                <tr>
                    <th>Logo</th>
                    <th>Název klubu</th>
                    <th>Místo</th>
                    <th class="text-right">Rok založení</th>
                    <th class="text-center">Počet členů</th>
                </tr>
            </thead>
            <tbody>
                {% for klub in kluby %}
                <tr>
                    <td>{% if klub.logo %}<img src="{{ klub.logo.url }}" alt="Logo {{ klub.nazev }}" class="logo-klubu rounded-pill">{% endif %}</td>
                    <td><b><a href="{% url 'detail_klubu' klub.id %}">{{ klub.nazev.upper }}</a></b></td>
                    <td>{{ klub.misto }}</td>
                    <td class="text-right">{{ klub.zalozeni }}</td>
                    <td class="text-center"><span class="badge-pill badge-danger">{{ klub.cyklista_set.count }}</span></td>
                </tr>
                </a>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

zavody/templates/page/footer.html
{% load static %}
<footer class="container p-3 bg-light border">
    <p class="text-center text-dark">Maturita: &copy; 2022 Viktor Hujer</p>
    <p class="text-center"><img src="{% static 'img/skola-logo.png' %}" alt="Logo školy"></p>
</footer>

zavody/templates/page/header.html
<header class="bg-primary p-3 text-center">
    <h1 class="display-3 text-white">BikeWeb</h1>
    <p class="text-warning">Stránky o amatérské cyklistice</p>
</header>

zavody/templates/page/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <a class="navbar-brand text-dark" href="#">BikeWeb</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="#">Úvodní stránka <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Novinky</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">Sezóny</a>
                <div class="dropdown-menu" aria-labelledby="dropdownId">
                    <a class="dropdown-item" href="#">2022</a>
                    <a class="dropdown-item" href="#">2021</a>
                    <a class="dropdown-item" href="#">2020</a>
                </div>
            </li>
        </ul>
    </div>
</nav>